### ISSUE TITLE
Name Missing from Contributors List

### ISSUE THREAD

**Issue by steveberdy** [dotnet/website-thanks-data#20]
Hi,

I was looking at the latest .NET release's list of contributors (https://dotnet.microsoft.com/en-us/thanks/) and was wondering why my name didn't show up. I made some contributions to .NET runtime and Roslyn Analyzers for .NET 6, but my name isn't on any .NET 6 contributors lists.

Thanks,
Steve

**Comment by mairaw** [comment]
For runtime, it might be because the commit was tagged with 6.0.1 and I still need to run the uploader for this specific release. Let me run that and see if your name will show up.

For roslyn-analyzer, adding @danzhu54 to comment. It might be because that repo doesn't follow the same tag versioning. 

/cc @sharwell

**Comment by steveberdy** [comment]
Thanks

**Comment by steveberdy** [comment]
By the way, the link for `/releases` in the Readme should probably be https://github.com/dotnet/core/releases instead of https://github.com/core/releses

**Comment by mairaw** [comment]
Thanks @steveberdy. Opened PR #21 for that.

**Comment by danzhu54** [comment]
We currently only have the immediate child repos of the dotnet/core release given by the github client API. For .NET 6.0.1 they are Aspnetcore, EF Core, Installer, Roslyn, Runtime, SDK, Windowsdesktop, winforms, and WPF.

**Comment by steveberdy** [comment]
@mairaw any updates? Thanks

**Comment by mairaw** [comment]
We're still investigating why your username is not showing up.

**Comment by mairaw** [comment]
@danzhu54 has found the root cause and we have published an update. Your name is now showing up under RC1.

Thanks for bringing this to our attention!

You can see below the before and after the update:
![image](https://user-images.githubusercontent.com/12971179/148319885-0d083bef-1af5-4524-8dce-dd0a9be90311.png)
